### ISSUE TITLE
Save log data periodically

### ISSUE THREAD

**Issue by Sejsel** [gw2scratch/evtc#109]
Currently, log data is only saved when the manager is closed. If it crashes or if it's killed for some reason, all processing progress is gone.

**Comment by cjahermanns** [comment]
Why not caching / storing the logs in a sqlite database instead of the json file? Could fix this issue and maybe improves app loading time when there are many logs?

**Comment by Sejsel** [comment]
That is certainly a good option, but requires more work than hotfixing the current issue. It would also make #28 even more problematic than it is now if implemented without taking that issue into account.

I would definitely like that eventually, or something similar to sqlite.

**Comment by cjahermanns** [comment]
Well that's probably true... You could try to work with ```System.Threading.Timer``` or ```System.Timers.Timer``` as a quick and dirty (kinda) fix I guess.

**Comment by Sejsel** [comment]
Implemented in 840b7026eb34a06ab1001b92bfed233d7d9ef2bc.
