### ISSUE TITLE
Add a way to filter logs by combination of players

### ISSUE THREAD

**Issue by tylercrompton** [gw2scratch/evtc#111]
I do fractals quite a lot. As my static experiments with various strats, we like to compare logs. Unfortunately, we frequently have to fill spots due to sporadic schedule conflicts. When digging through logs, I have to click on each one to see who was in the run. It'd be nice to be able to filter for more than one account. I only want to see logs where all five of us were present. I'm aware of the Players tab, but that's insufficient because it only allows filtering for one account.

**Comment by Sejsel** [comment]
I have finally implemented this in 4ae0e9fbe017f9e7f50172568f38c832d57add84. For now, it's only accounts and not specific characters, but that should already be a big improvement.

It will be available in the next released version.
