### ISSUE TITLE
Dragonhunter & Firebrand Not Recognized As Guardian

### ISSUE THREAD

**Issue by Arkkhalis64** [gw2scratch/evtc#129]
**Statistics**
Guardian elite specializations are not counted towards profession count.
![StatisticsTab](https://user-images.githubusercontent.com/75038350/128403664-01a466fc-e59a-48e9-87dc-d1d3610c47eb.png)

**Players**
Guardian elite specializations display as Unknown Profession instead of Guardian.
![PlayersTab](https://user-images.githubusercontent.com/75038350/128403753-fa564ebf-8403-4ee8-825f-0c947347b049.png)

**Comment by Sejsel** [comment]
Thank you for the report, this bug is fixed already (in 34d69f3af3), but there hasn't been a release since that fix was added. I should hopefully get one out soon :)
