### ISSUE TITLE
In parsing phase the progress it not really visible.

### ISSUE THREAD

**Issue by it-rec** [gw2scratch/evtc#130]
**Version:** 
1.1.1.0

**Issue:** 
When launching the log manager, on the bottom leftit shows how many logs are found and how many are being parsed. Even though there is tons of space it crops it making it not visible any longer.

![grafik](https://user-images.githubusercontent.com/19797875/129474064-d7527ac8-62aa-447d-907e-fa908a54ccfd.png)

**Comment by Sejsel** [comment]
I don't think there's any cropping here. The ellipsis is always added, I suppose I could remove it to make it more clear.

**Comment by it-rec** [comment]
> 
> 
> I don't think there's any cropping here. The ellipsis is always added, I suppose I could remove it to make it more clear.

Allright. Thank you for clearifig this! 

Ahh now I assume I get it: The right number is accumulacted and may grow any time, while the left one is showing what has already progressed. So both numbers change. Maybe writing something like `Found x logs, processed y of them` would make it clearer.

**Comment by Sejsel** [comment]
This should be resolved with a6b8046a3e347e52c16079d4d8280147248dd03b.

Total log count is now separate from processing progress, and it shows the number of logs according to the current filters as well.
