### ISSUE TITLE
Processing log files takes long, even though caching is on

### ISSUE THREAD

**Issue by it-rec** [gw2scratch/evtc#131]
**Version:** 
1.1.1.0

**Issue:**
I do not often use the log manger, more like ones in a month or a bit lesss. I noticed that until I see any log it takes like minutes where it searches and parses logs. Looking at the load of my CPU shows that the cores are bored and some even have nearly no load at all:

![grafik](https://user-images.githubusercontent.com/19797875/129474316-9cce5a41-8bb3-47a0-aa61-bf30153f8e3f.png)

**Comment by Sejsel** [comment]
Just to make sure, what is your log directory set to in the settings? If it's set to something like `C:/`, the log manager would have to look through the entire drive to look for logs, which would be slow.

Assuming it's not that issue, the log processing is often bound by IO performance, especially on hard drives. However, on fast SDDs, you may be bound by CPU processing, and only one core is currently used to process the logs. This is definitely something that could be improved in the future.

**Comment by it-rec** [comment]
**My log directory is set to:**
`D:\<MyUserName>\Documents\Guild Wars 2\addons\arcdps\arcdps.cbtlogs`

**My hard drive**
The log manager and the logs are on a SSD, I could move them to my M2 but I assume that is not it.

When it only executes on one core that could explain it. I mean for tons of logs that could really make a difference, if you'd fan out the work on as many threads as the user got cores it could really greatly improve performance. But I'm not sure how, say six threads and respective read from the drive really performes and if some zero buffer appraoch could work for another thing to look at. But I'm sure if you tinker a bit, you find our yourself best :)

> This is definitely something that could be improved in the future.
Great!

**Comment by marcustyphoon** [comment]
Check and see if your antivirus is activating while the manager is parsing. I had a weird issue where it would re-scan every file and this made it took an order of magnitude longer than it ought to have! Certainly might not be relevant, but worth a check.

**Comment by it-rec** [comment]
> 
> 
> Check and see if your antivirus is activating while the manager is parsing. I had a weird issue where it would re-scan every file and this made it took an order of magnitude longer than it ought to have! Certainly might not be relevant, but worth a check.

Nope, did not help. Thank you though for the suggestion!

**Comment by Sejsel** [comment]
This should be significantly better after c8b86ec6eea4ce5fdc3da3748f498eb8d49611ef and cae09fde90786c90aaa6b62390ef10e444b16c48, especially if you had non-log files in the directory - notably reports generated by the gw2wingman uploader.

If you could let me know if it performs better after 1.2.1 is released (should be later today), that would be very welcome :)

**Comment by it-rec** [comment]
> especially if you had non-log files in the directory - notably reports generated by the gw2wingman uploader

Indeed!

> If you could let me know if it performs better after 1.2.1 is released (should be later today), that would be very welcome :)

It performs way better now. I feel a significant change in speed! Thank you for the quick response and improvement. I'm amazed!

**Comment by it-rec** [comment]
Closing the issue.
