### ISSUE TITLE
Add icons for remaining EoD elite specilizations

### ISSUE THREAD

**Issue by Sejsel** [gw2scratch/evtc#142]
Currently, there are no wiki Tango icons available for 4 out of the new elite specializations. The wiki is currently having some questionable arguments about not using them anymore, so it is very unclear whether new ones will be produced, and when. We should find some temporary solution until EoD release and see then.

- [x] Bladesworn
- [x] Vindicator
- [x] Catalyst
- [x] Mechanist
- [x] Specter
- [x] Untamed

We also need to make it clear which icons have which license if we end up mixing tango icons with official ANet ones.

**Comment by EliphasNUIT** [comment]
The tangos for everything except Specter and Catalyst seem to be ready.
On EI I'm linking to those:
https://wiki.guildwars2.com/images/thumb/c/c1/Bladesworn_tango_icon_200px.png/20px-Bladesworn_tango_icon_200px.png
https://wiki.guildwars2.com/images/5/5a/Vindicator_tango_icon_20px.png
https://wiki.guildwars2.com/images/thumb/8/8a/Mechanist_tango_icon_200px.png/20px-Mechanist_tango_icon_200px.png
https://wiki.guildwars2.com/images/thumb/3/33/Untamed_tango_icon_200px.png/20px-Untamed_tango_icon_200px.png

**Comment by Sejsel** [comment]
Only Catalyst and Specter is missing now, after adding the existing icons in 0bcffc29e44d7fc7d465747aefffa91b13765415.

**Comment by Sejsel** [comment]
This is done with 5b6f27ebc1c9e83ad743889bff1ed7392e5e341b.
