### ISSUE TITLE
HTCM False Success

### ISSUE THREAD

**Issue by sp4ghet** [gw2scratch/evtc#187]
Some of my logs from HTCM are falsely counted as successes although they were soo-won 2 wipes.

https://dps.report/bewu-20230416-220041_void
https://dps.report/DfJp-20230416-212433_void
https://dps.report/ZG1D-20230416-211031_void

I've put the bugged log files in this repo if that helps.
https://github.com/sp4ghet/evtc_bug_report

Here is a screenshot of arcdps Log Manager 1.8.0.0 which shows these as success logs
![image](https://user-images.githubusercontent.com/8775460/232675890-f9a58abc-4991-4d77-ab0f-98f5cf90ea79.png)

**Comment by Sejsel** [comment]
This should be fixed with Log Manager v1.11, if you find any logs that are detected wrong even with the latest version, please reopen the issue. Thanks!
