### ISSUE TITLE
Missing category icons for Cosmic Observatory and Temple of Febe

### ISSUE THREAD

**Issue by Linkaaaaa** [gw2scratch/evtc#208]

**Comment by Sejsel** [comment]
Fixed in 6680e07.

**Comment by Linkaaaaa** [comment]
I had picked the images to be loading screens just like the eod strikes, i guess i can just close the pull request then?

**Comment by Sejsel** [comment]
Oh, I somehow missed the PR, my bad. I do think the minis do work better, though, they are recognizable better, and we have them (unlike for EoD strikes where only Mini Mai Trin existed and only from older content).
