### ISSUE TITLE
HTCM false failures

### ISSUE THREAD

**Issue by michaelwang314** [gw2scratch/evtc#210]
With the new update, a lot of false failures were fixed.  However this recent successful log I got shows up as Failure (16%) in log manager.  Not sure if these files are uploaded correctly here

https://dps.report/sUGe-20231016-205708_void
[log.zip](https://github.com/gw2scratch/evtc/files/12923664/log.zip)
![image](https://github.com/gw2scratch/evtc/assets/58545313/058e4e0e-b1f3-4a35-83a8-f8cb1099cc81)

**Comment by Linkaaaaa** [comment]
It was fixed last week on elite insights with a 150ms threshold https://github.com/baaron4/GW2-Elite-Insights-Parser/commit/8a2c73c4776bcbf494d24dea99dd7a825a726faa

**Comment by Sejsel** [comment]
Should be fixed with 520bff5529d28dd815bc3288264dbe6acd41647e which will go out with the next update. I also added an anonymized version of the log into the log testing suite. Thanks for the report!
