### ISSUE TITLE
[Inspector] Add the new CBTS events

### ISSUE THREAD

**Issue by Linkaaaaa** [gw2scratch/evtc#227]
- [x] mar.28.2024: evtc: added cbts_squadmarker, src and dst agent are float xyz, skillid is index. inf if not set.
- [x]  mar.28.2024: evtc: added a cbts_marker event for markers being removed (id 0).
- [x]  mar.28.2024: evtc: added cbts_marker events for agents that have a marker added (in addition to at log start).

**Comment by Linkaaaaa** [comment]
jun.14.2024: evtc: added cbts_arcbuild, src_agent is null-terminated full version string as in arcdps.log.

**Comment by Sejsel** [comment]
Support for arcdps build added in eb3d4c27ca493e9d88d8f82def3f9d7dba806678, it now is also shown in the statistics tab in the Inspector.

**Comment by Linkaaaaa** [comment]
jun.27.2024: evtc: above is cbtr_crowdcontrol (12) in combat result enum, as direct damage event.
 jun.27.2024: evtc: added cbts_glider, value = 1 or 0 for deployed or stowed.
 jun.27.2024: evtc: changed cbts_weapswap, value is now the old set.

**Comment by Sejsel** [comment]
Glider events added in d3b4bd7f00e17fab28b444462ddcb4348740962f.

**Comment by Sejsel** [comment]
Old weapon swap set added in 0d5c1822ba0ff44a3dd4df0fca1236c6c19f3b6e.

**Comment by Sejsel** [comment]
Crowd control events added in af1092b073db6b5bbf719c4b5a2011fae16f3d18.

**Comment by Sejsel** [comment]
Added `SquadGroundMarkerPlace`, `SquadGroundMarkerRemove`, `AgentMarkerRemoveAllEvent`. With that, all of these should be implemented, closing.
