### ISSUE TITLE
Add a way to delete logs

### ISSUE THREAD

**Issue by Sejsel** [gw2scratch/evtc#71]
Add a button to delete logs for any selection. For example finding failure logs older than a specific date is doable with filters, and you can just select all and then click delete to save a lot of space.

This hasn't been done earlier because detections were not good enough, but that we are getting close to 1.0.0 I am pretty confident in them.

**Comment by Linkaaaaa** [comment]
The commit https://github.com/gw2scratch/evtc/pull/117/commits/66715ab01811e0e3ecd0b4a420bcdca06e057523 fixes the issue #31
