### ISSUE TITLE
Ai, Keeper of The peak CM logs report failure between >101 and 100% for day phase

### ISSUE THREAD

**Issue by olibertos** [gw2scratch/evtc#99]
[Ai-DayNightSamples.zip](https://github.com/gw2scratch/evtc/files/5685040/Ai-DayNightSamples.zip)
Please find attached samples for success and failures for day/night, and combined day/night, hopefully they help!

**Comment by Sejsel** [comment]
Right now Ai logs are only marked as success if you kill it in the dark phase, thanks for the report, this definitely needs to be improved as resetting between the two phases is common.

**Comment by Sejsel** [comment]
Solved with 9aebba81a30abacc0b8529907d3e6963a661068b, the log manager now differentiates between the three possible log types, and considers a day-only log that gets to the invulnerability a success. The change will be included in the next update :)
